config/routes.rb
Rails.application.routes.draw do
  
  get 'carts/show'
  resources :searches
  resources :orders
  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'
  resources :products
  devise_for :borrowers
  resources :borrowers
  devise_for :borrowees
  resources :borrowees, :only => [:index]
  root 'pages#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/borrowee.rb
class Borrowee < User
	has_many :products, dependent: :destroy
end

app/models/borrower.rb
class Borrower < User
	has_many :orders
end

app/models/cart.rb
class Cart < ApplicationRecord

	def items_count
  	order.items.sum(:quantity)
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :borrower
	before_save :update_total
  before_save :update_status

  def calculate_total
    self.order_items.map { |item| item.product.price * item.quantity * (item.return_date - Date.today)  }.sum
  end

  private

  def update_status
  	self.status = "Cart"
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  attr_reader :return_days
  # before_save :days_to_return_date
  

  # def days_to_return_date
  # 	self.return_date = Date.today + return_days.to_i
  # end
  def return_days=(days)
  	self.return_date = Date.today + days.to_i
  end

 
end




#

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :borrowee
	has_many   :order_items
	validates  :borrowee_id, presence: true
	validates  :name, presence: true, length: { in: 6..20 }
	# validates  :size, presence: true
	validates  :price, presence: true, numericality: true



	def size 
		#Product.column_names.select{|i| i[("size")]}
		q = {s: size_s, xs: size_xs, m: size_m, l: size_l, xl: size_xl}
		q.select{|key, value| value.eql?(true) }.keys.join(',')
	end


end

app/models/search.rb
class Search < ApplicationRecord

	def search_products
		products = Product.all

		products = products.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		products = products.where(:size_s => true) 
		# products = products.where(:size_xs => true) if size_xs.present?
		products = products.where(["price >= #{min_price}"]) if min_price.present?
		products = products.where(["price <= #{max_price}"]) if max_price.present?
		# products = products.where(:size_l => true) 
		return products
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates  :name,:email,:phone,:address,:city,:pincode, presence: true
  validates  :phone, numericality: true, length: {is: 10}
  validates  :address, length: {maximum: 60}
  validates  :pincode, length: {is: 6}


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    @order_items = current_order.order_items
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :user_authentication
  
  def index
  end

  private
  def user_authentication
  	if borrowee_signed_in?
  	 redirect_to borrowees_path
  	
    elsif borrower_signed_in?
  	 redirect_to products_path
  	else
  	 	render 'pages/index'
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user! 

  def index
    if params[:search]
      @products = Product.where(["name LIKE ?","%#{params[:search]}%"])
    elsif 
      @products = Product.all
    end
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = current_user.products.build(product_params)
    if @product.save
     flash[:success] = "Product Added"
  	 redirect_to borrowees_path(@borrowee)
    else
      flash.now[:error] = @product.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end

  def edit
  end

  def destroy
    @product = current_user.products.find_by(id: params[:id])
    @product.destroy
    redirect_to borrowees_path(@borrowee)
  end

  private
  def product_params
  	params.require(:product).permit(:name, :size_s, :size_xs, :size_m, :size_l, :size_xl, :color, :price)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new
		@search = Search.new
	end

	def create
		@search = Search.create(search_params)
		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
		# debugger 
	end

	private
	def search_params
		params.require(:search).permit(:keywords, :max_price, :min_price, :size_xs, :size_s, :size_m, :size_l, :size_xl)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrowees_helper.rb
module BorroweesHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/orders/index.html.erb
<table class = "table">
  <tr>
  	<th>Name</th>
    <th>Size</th>
    <th>Color</th>
    <th>return_date</th>
    <th>total </th>
  </tr>
	<% if @order.any? %>
	  <% @order.each do |item| %>
		  <% item.order_items.each do |x| %>
			  <tr>
			  	<td><%= x.product.name %> </td>
			    <td><%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"}%></td> 
			  </tr>
			<% end %>
	  <% end %>
	<% else %>
	  <p>Your shopping cart is empty.</p>
	<% end %>
</table>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h3>Search_By_Name: </h3> <%= form_tag products_path, :method =>'get' do  %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
<%= link_to "filters", new_search_path %>


<table class = "table">
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Color</th>
    <th>price</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.size %></td>
    <td><%= product.color %></td>
    <td><%= product.price %></td>
    <td><%= link_to "show", product_path(product) %>
  </tr>
<% end %>
</table>

app/views/products/new.html.erb
<h1>Add Products</h1>
<div class="container" style="margin-left: 16%">
		<div class="form-group">
		<%= form_with model: @product do |f| %> 

			<%= f.label :name , class:"control-label col-sm-2"%>
			<%= f.text_field :name, class: "col-sm-4"%>
			<br>
			<br>
			<%= f.label :size, class:"control-label col-sm-2"%>
			<%= f.check_box :size_xs%>
			<%= f.label(:xs, "Xtra-Small") %>
			<%= f.check_box :size_s%>
			<%= f.label(:s, "Small") %>
			<%= f.check_box :size_m %>
			<%= f.label(:m, "Medium") %>
			<%= f.check_box :size_l %>
			<%= f.label(:l, "Large") %>
			<%= f.check_box :size_xl %>
			<%= f.label(:xl, "Xtra-Large") %>
			<br>
			<br>
			<%= f.label :color, class: "control-label col-sm-2" %>
			<%= f.text_field :color, class: "col-sm-4" %>
			<br>
			<br>
			<%= f.label :price, class: "control-label col-sm-2" %>
			<%= f.text_field :price, class: "col-sm-4" %>
			<br>
			<br>
			<div style="margin-left:18%">
				<%= f.submit  %>
			</div>

		<% end %> 
	</div>
</div>

app/views/products/show.html.erb
<div class = "row">
	<div class = "col-md-4">
		<h5> Name: </h5>
		<h5> Size: </h5>
		<h5> Color: </h5>
		<h5> price: </h5>
	</div>
	<div class = "col-md-4">
		<%= @product.name %> <br>
		<%= @product.size %> <br>
    <%= @product.color %> <br>
		<%= @product.price%> <br>
	</div>
	<div class = "col-md-4">
		<%= render 'order_items/new' %>
	</div>
</div>

app/views/searches/new.html.erb
<%= form_for @search, html: {class: "pure-form"} do |f| %>
	<div class = "field">
		<%= f.label :keywords %>
		<%= f.text_field :keywords %>
	</div>

	<div class = "field">
		<%= f.label :min_price %>
		<%= f.text_field :min_price %>
	</div>

	<div class = "field">
		<%= radio_button_tag(:size_s, "size_s") %>
		<%= label_tag(:size_s, "size_s") %>
	</div>

	<div class = "field">
		<%= radio_button_tag(:size_xs, "size_xs") %>
		<%= label_tag(:size_xs, "size_xs") %>
	</div>

	<div class = "field">
		<%= radio_button_tag(:size_m, "size_m") %>
		<%= label_tag(:size_m, "size_m") %>
	</div>

	<div class = "field">
		<%= radio_button_tag(:size_l, "size_l") %>
		<%= label_tag(:size_l, "size_l") %>
	</div>

	<div class = "field">
		<%= radio_button_tag(:size_xl, "size_xl") %>
		<%= label_tag(:size_xl, "size_xl") %>
	</div>

	<div class = "field">
		<%= f.label :max_price %>
		<%= f.text_field :max_price %>
	</div>

	<div class = "action"> <%= f.submit "search" , class:"pure-button pure-button-primary"%> </div>
<% end %>

app/views/searches/show.html.erb
<% if @search.search_products.empty?  %>
		<p> No Record Found </p>
	<% else %>
	<% @search.search_products.each do |x| %>
		<%= x.name %> <br>
		<%= x.size %> <br>
		<%= x.color %> <br>
		<%= x.price %> <br>
		<br>
	<% end %>
<% end %>
<%= link_to "back", new_search_path %>