config/routes.rb
Rails.application.routes.draw do
  
  get 'carts/show'
  resources :searches
  resources :orders
  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'
  resources :products
  devise_for :borrowers
  resources :borrowers
  devise_for :borrowees
  resources :borrowees, :only => [:index]
  root 'pages#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/borrowee.rb
class Borrowee < User
	has_many :products, dependent: :destroy
end

app/models/borrower.rb
class Borrower < User
	has_many :orders
end

app/models/cart.rb
class Cart < ApplicationRecord

	def items_count
  	order.items.sum(:quantity)
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :borrower
	before_save :update_total
  before_save :update_status

  def calculate_total
    self.order_items.map { |item| item.product.price * item.quantity * (item.return_date - Date.today)  }.sum
  end

  private

  def update_status
  	self.status = "Cart"
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  attr_reader :return_days
  # before_save :days_to_return_date
  

  # def days_to_return_date
  # 	self.return_date = Date.today + return_days.to_i
  # end
  def return_days=(days)
  	self.return_date = Date.today + days.to_i
  end

 
end




#

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :borrowee
	has_many   :order_items
	validates  :borrowee_id, presence: true
	validates  :name, presence: true, length: { in: 6..20 }
	# validates  :size, presence: true
	validates  :price, presence: true, numericality: true



	def size 
		#Product.column_names.select{|i| i[("size")]}
		q = {s: size_s, xs: size_xs, m: size_m, l: size_l, xl: size_xl}
		q.select{|key, value| value.eql?(true) }.keys.join(',')
	end


end

app/models/search.rb
class Search < ApplicationRecord

	def search_products
		products = Product.all

		products = products.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		products = products.where(:size_s => true) 
		# products = products.where(:size_xs => true) if size_xs.present?
		products = products.where(["price >= #{min_price}"]) if min_price.present?
		products = products.where(["price <= #{max_price}"]) if max_price.present?
		# products = products.where(:size_l => true) 
		return products
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates  :name,:email,:phone,:address,:city,:pincode, presence: true
  validates  :phone, numericality: true, length: {is: 10}
  validates  :address, length: {maximum: 60}
  validates  :pincode, length: {is: 6}


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :user_authentication
  
  def index
  end

  private
  def user_authentication
  	if borrowee_signed_in?
  	 redirect_to borrowees_path
  	
    elsif borrower_signed_in?
  	 redirect_to products_path
  	else
  	 	render 'pages/index'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrowees_helper.rb
module BorroweesHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_borrowee_signed_in.html.erb
<li><%= link_to "Add Product", new_product_path %> </li>
<li><%= link_to 'Log out', destroy_borrowee_session_path, method: :delete %></li>
<li><%= link_to 'Edit Profile' , edit_borrowee_registration_path, method: :get %></li>
<li><%= link_to "My products" , borrowees_path %> </li>

app/views/layouts/_borrower_signed_in.html.erb
<li><%= link_to 'Log out', destroy_borrower_session_path, method: :delete %></li>
<li><%= link_to 'Edit_details' , edit_borrower_registration_path, method: :get %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClothRentalStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.nil? %>
    <%else %>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if borrower_signed_in? %>
                <%= render 'layouts/borrower_signed_in' %>
              <% end %>
              <% if borrowee_signed_in? %>
                <%= render 'layouts/borrowee_signed_in' %>
              <% end%>
            </ul>
          </nav>
        </div>
      </header>
    <% end %>
    <div class="container">
      <% if flash.present? %>
        <ul>
          <% flash.each do |key, message| %>
            <li class="<%= key %>"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClothRentalStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
    	body { 
  		padding-top: 80px; 
  		font-family: Arvo; 
  		background-image: url(/assets/13.jpg); 
			}
			h1{
				text-align: left;
				color: white;
				margin-top: 0px;
			}
			h3{
				color: white;
			}

    </style>
  </head>
 <body>
 	<b> <h1> THE FUTURE OF OUR WARDDROBE <STRONG>RENTAL CLOTHES...</STRONG> </h1> </b>
 	<h3 > YOU ARE ? SELECT: </h3>
 	<STRONG><h5><%= link_to "Borrower" , borrower_session_path, :class=> 'top-left' %></h5></STRONG>
 	<strong><h5><%= link_to "Borrowee" , borrowee_session_path, :class=> 'top-right' %></h5></strong>
  </body>
</html>